apiVersion: v1
data:
  trackingdb.user.name: {{ .Values.credentials.dbusername }}
  trackingdb.user.password: {{ .Values.credentials.dbpassword }}
  rabbitmq.user.name: {{ .Values.credentials.mqusername }}
  rabbitmq.user.password: {{ .Values.credentials.mqpassword }}   
kind: Secret
metadata:
  name: cargotracker-tracking-credentials
type: Opaque